language: ruby
script: rspec spec
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - rbx
  - jruby-18mode
  - jruby-19mode
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-18mode
    - rvm: jruby-19mode
    - rvm: ruby-head
